### ISSUE TITLE
not working in Django admin

### ISSUE THREAD

**Issue by evilscientress** [raphaelm/django-i18nfield#18]
I tried using it the i18n field in Django 2.1.7 and 2.2 and in both Version the fields don't work without creating a ModelForm that explicitly maps the field to the I18nTextInput or I18nTextarea.

The root cause seams to be that the `formfield_for_dbfield` function that iterates over the mro of the I18n fields and looks up kwargs in the `formfield_overrides` dict and then sets the widget kwarg to `django.contrib.admin.widgets.AdminTextareaWidget` which causes the I18nFormField class to use the wrong widget in line [180](https://github.com/raphaelm/django-i18nfield/blob/master/i18nfield/forms.py#L180) of forms.py

```
Traceback (most recent call last):
  File "[redacted]/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "[redacted]/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "[redacted]/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "[redacted]/env/lib/python3.6/site-packages/django/contrib/admin/options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "[redacted]/env/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "[redacted]/env/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "[redacted]/env/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "[redacted]/env/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1634, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "[redacted]/env/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "[redacted]/env/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "[redacted]/env/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "[redacted]/env/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1551, in _changeform_view
    ModelForm = self.get_form(request, obj, change=not add)
  File "[redacted]/env/lib/python3.6/site-packages/django/contrib/admin/options.py", line 669, in get_form
    fields = flatten_fieldsets(self.get_fieldsets(request, obj))
  File "[redacted]/env/lib/python3.6/site-packages/django/contrib/admin/options.py", line 330, in get_fieldsets
    return [(None, {'fields': self.get_fields(request, obj)})]
  File "[redacted]/env/lib/python3.6/site-packages/django/contrib/admin/options.py", line 321, in get_fields
    form = self._get_form_for_get_fields(request, obj)
  File "[redacted]/env/lib/python3.6/site-packages/django/contrib/admin/options.py", line 659, in _get_form_for_get_fields
    return self.get_form(request, obj, fields=None)
  File "[redacted]/env/lib/python3.6/site-packages/django/contrib/admin/options.py", line 705, in get_form
    return modelform_factory(self.model, **defaults)
  File "[redacted]/env/lib/python3.6/site-packages/django/forms/models.py", line 551, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "[redacted]/env/lib/python3.6/site-packages/django/forms/models.py", line 256, in __new__
    apply_limit_choices_to=False,
  File "[redacted]/env/lib/python3.6/site-packages/django/forms/models.py", line 176, in fields_for_model
    formfield = formfield_callback(f, **kwargs)
  File "[redacted]/env/lib/python3.6/site-packages/django/contrib/admin/options.py", line 185, in formfield_for_dbfield
    return db_field.formfield(**kwargs)
  File "[redacted]/env/lib/python3.6/site-packages/i18nfield/fields.py", line 48, in formfield
    return super().formfield(**defaults)
  File "[redacted]/env/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 2084, in formfield
    **kwargs,
  File "[redacted]/env/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 891, in formfield
    return form_class(**defaults)
  File "[redacted]/env/lib/python3.6/site-packages/i18nfield/forms.py", line 180, in __init__
    locales=self.locales, field=self, **kwargs.pop('widget_kwargs', {})
TypeError: __init__() got an unexpected keyword argument 'locales'
```

**Comment by raphaelm** [comment]
Hmm, yeah, that doesn't sound good. I'm sure there is an easy way to prevent it, but since I do not use this library in any project that uses Django admin, it's unlikely I'll find the time to look into it. :(

**Comment by oldcai** [comment]
I've met this problem too. I thought it was my misuse caused the error.

For now, the only way to avoid this problem is to create a ModelForm like you said.

**Comment by luto** [comment]
```python
import i18nfield.fields
import i18nfield.forms

class I18nModelAdmin(admin.ModelAdmin):
    formfield_overrides = {
        i18nfield.fields.I18nTextField: {'widget': i18nfield.forms.I18nTextarea},
        i18nfield.fields.I18nCharField: {'widget': i18nfield.forms.I18nTextInput},
    }

class SomeConcreteAdmin(I18nModelAdmin):
  # ...
```

This is shorter and easier to use, imho.

@raphaelm let me know, if you'd like me to add a PR, which
* adds this class to i18nfield
* replaces [these docs](https://django-i18nfield.readthedocs.io/en/latest/admin.html) with the `SomeConcreteAdmin` example above

**Comment by luto** [comment]
Alternatively something like

```python

class I18nModelAdmin(admin.ModelAdmin):
    formfield_overrides_defaults = {
        i18nfield.fields.I18nTextField: {"widget": i18nfield.forms.I18nTextarea},
        i18nfield.fields.I18nCharField: {"widget": i18nfield.forms.I18nTextInput},
    }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # ensure django admin uses the special i18n widges, but allow child
        # classes to override them using formfield_overrides_defaults.
        for k, v in self.formfield_overrides_defaults.items():
            self.formfield_overrides.setdefault(k, v)
```

Which doesn't block you from using `formfield_overrides` in `SomeConcreteAdmin`.

**Comment by raphaelm** [comment]
Sounds like a great way, would merge that PR :)
