### ISSUE TITLE
Cannot order_by on I18nTextField

### ISSUE THREAD

**Issue by warvariuc** [raphaelm/django-i18nfield#37]
This is really weird, and I would appreciate help, as I've spent several hours debugging this.

I have a model:

```
class TestingStandardGroup(TimeStampedModel):
    name = I18nCharField()
    #name = I18nTextField()

```

And I have this query:
```
aa = TestingStandardGroup.objects.all().order_by('name__en')
```

If I change `name` field type from `I18nCharField` to `I18nTextField`, the query breaks:

```
*** django.core.exceptions.FieldError: Cannot resolve keyword 'en' into field. Join on 'name' not permitted.
Traceback (most recent call last):
  File "/Users/vic/projects/txc/.venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1642, in transform
    return self.try_transform(wrapped, name)
  File "/Users/vic/projects/txc/.venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1224, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'en' for I18nTextField or join on the field not permitted.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pdb.py", line 366, in displayhook
    self.message(repr(obj))
  File "/Users/vic/projects/txc/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 256, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "/Users/vic/projects/txc/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/Users/vic/projects/txc/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/vic/projects/txc/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/vic/projects/txc/.venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1162, in execute_sql
    sql, params = self.as_sql()
  File "/Users/vic/projects/txc/.venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 513, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/Users/vic/projects/txc/.venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 56, in pre_sql_setup
    order_by = self.get_order_by()
  File "/Users/vic/projects/txc/.venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 356, in get_order_by
    order_by.extend(self.find_ordering_name(
  File "/Users/vic/projects/txc/.venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 769, in find_ordering_name
    return [(OrderBy(transform_function(t, alias), descending=descending), False) for t in targets]
  File "/Users/vic/projects/txc/.venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 769, in <listcomp>
    return [(OrderBy(transform_function(t, alias), descending=descending), False) for t in targets]
  File "/Users/vic/projects/txc/.venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1646, in transform
    raise last_field_exception
  File "/Users/vic/projects/txc/.venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1623, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "/Users/vic/projects/txc/.venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1569, in names_to_path
    raise FieldError(
(Pdb++)
```

Which doesn't make sense to me, as both fields differ only with name and widget:
```
class I18nCharField(I18nFieldMixin, models.TextField):
    widget = I18nTextInput


class I18nTextField(I18nFieldMixin, models.TextField):
    widget = I18nTextarea
```

Using 1.9.3 with Django 3.2.4 and Postgres.

Another question. Looking through the `django-i18nfield` code I don't see how Django understands to treat the field as `json`:

```
(Pdb++) str(aa.query)
'SELECT ... ORDER BY "txc_testingstandardgroup"."name"::json->>\'en\' ASC'
```

**Comment by raphaelm** [comment]
Sorry, sorting is not supported by the library's current approach at all. The fields are also not treated as JSON by the database at all. This project is *years* older than cross-database JSONField support in Django. We'd very much like to convert this to JSONField all day, and it should be pretty easy to create a new library that works the same way but with JSONField, however changing this library will require figuring out how to easily migrate projects that already have hundreds of fields in tables with millions of lines. I haven't yet been able to put in the time to figure that out.

**Comment by warvariuc** [comment]
Sorry, found the problem, which is project specific:

```
class I18nTransform(Transform):
    def __init__(self, *args, **kwargs):
        self.template = f"%(expressions)s::json->>'{self.lookup_name}'"
        super().__init__(*args, **kwargs)


for lang, _ in settings.LANGUAGES:
    class Lookup(I18nTransform):
        lookup_name = lang

    I18nCharField.register_lookup(Lookup)
```

**Comment by rixx** [comment]
Looking at a possible migration to `JsonField` a bit more, I think the biggest change required in current code, as well as the biggest upgrading hurdle, is the fact that currently, django-i18nfield does not prevent users from writing plain strings to the database – so we'd need to decide what to do with plain strings in the future, and during migration, decide which fallback language code to assign to plain strings already existing in the database.

**Comment by raphaelm** [comment]
Hmm, the cleanest way might be to store this as {"_": "string"} so we can build proper fallbacks for old data?

I'd really love to move to jsonfield, but I'm really scared of the migration process :D
